<hr id="import">

<h2> Q1</h2>

In [1]:
#import libraries
import pandas as pd

In [5]:
#load the data
data = pd.read_csv(r'Third Year Grades - Semester 2.csv')
data.head()

,Student ID,Full Name,Mass Transfer,Heat transfer,Process and Plant,Petroleum Geology,Poduction-2,Probability,Control-2
0,101,Ahmed Mohamed Ali,85,92,78,90,87,95,82
1,102,Mohamed Hassan Ibrahim,75,80,85,72,88,90,77
2,103,Nour Ibrahim Abdel-Rahman,90,95,92,88,91,98,90
3,104,Hala Mohamed Ahmed,82,85,78,80,85,92,87
4,105,Ali Hassan Hussein,70,75,80,78,82,85,77

In [46]:
    def assign_grade(percentage):
        if 93 <= percentage <= 100:
              return 4.0  # A
        elif 89 <= percentage < 93:
              return 3.7  # A-
        elif 84 <= percentage < 89:
                return 3.3  # B+
        elif 80 <= percentage < 84:
               return 3.0  # B
        elif 76 <= percentage < 80:
              return 2.7  # B-
        elif 72 <= percentage < 76:
             return 2.3  # C+
        elif 68 <= percentage < 72:
            return 2.0  # C
        elif 64 <= percentage < 68:
                 return 1.7  # C-
        elif 60 <= percentage < 64:
             return 1.3  # D+
        else:
            return 0.0  # F

    def course_credits(course_name):
        if course_name == 'Mass Transfer':
              return 3
        elif course_name == 'Heat Transfer':  # Fixed typo here
                return 3
        elif course_name == 'Process and Plant':
            return 2
        elif course_name == 'Petroleum Geology':
            return 3
        elif course_name == 'Production-2':  # Fixed typo here
            return 2
        elif course_name == 'Probability':
             return 3
        elif course_name == 'Control-2':
             return 3

    


    # Create a list to store the GPAs
    gpa_list = []

    # Calculate GPA for each student and store it in the list
    for index, row in data.iterrows():
        total_points = 0
        total_credits = 0
        for course in ['Mass Transfer', 'Heat Transfer', 'Process and Plant', 'Petroleum Geology', 'Production-2', 'Probability', 'Control-2']:
            if course in row:
                grade = assign_grade(row[course])
                credits = course_credits(course)
                total_points += grade * credits
                total_credits += credits
        gpa = total_points / total_credits
        gpa_list.append((row['Full Name'], gpa))

    # Sort the list of GPAs in descending order
    gpa_list.sort(key=lambda x: x[1], reverse=True)

    # Print the sorted GPAs
    for name, gpa in gpa_list:
        print(f"{name}, {gpa:.2f}")

Youssef Hassan Ali, 4.00
Laila Hassan Ibrahim, 4.00
Israa Hassan Mostafa, 4.00
Nour Ibrahim Abdel-Rahman, 3.70
Sara Mohamed Ahmed, 3.70
Hala Mohamed Ahmed, 3.30
Omar Hassan Ibrahim, 3.30
Hana Mohamed Ali, 3.30
Tamer Mohamed Ahmed, 3.30
Ahmed Mostafa Ali , 3.30
Hayam Mohamed Magdy, 3.30
Keolos Mina Yohana , 3.30
Ahmed Mohamed Ali, 3.00
Mohamed Hassan Ibrahim, 2.70
Ali Hassan Hussein, 2.70
Mariam Mohamed Ahmed, 2.70
Karim Mohamed Ahmed, 2.70
Mona Mohamed Ahmed, 2.70
Ayman Mostafa Ehab, 2.70
Seif Eldin Ehab , 2.70

<hr id="import">

<h2>Q2</h2>

In [32]:
# Prompt the user to enter the size of the particles in meters and the density of solid particles in Kg.m-3
Dp = float(input("Enter the size of the particles in meters: "))

row_p = float(input("Enter the density of solid particles in Kg.m-3: "))

row_f = 1000
meo_f = 0.001
g = 9.8
K = Dp * ((g * row_f * (row_p - row_f) / meo_f**2))**(1/3)

if K < 2.62:
    vt = (g * Dp**2 * (row_p - row_f)) / (18 * meo_f)
    print(f"The fluid flow is in the laminar regime \n The terminal Velocity= {vt:.4f}")
elif 2.62 < K < 69.3:
    vt = ((g * Dp**1.61 * (row_p - row_f)) / (14 * meo_f**0.61 * row_f**0.39)) * (1 / 1.39)
    print(f"The fluid flow is in the intermediate regime \n The terminal Velocity= {vt:.4f}")
else:
    vt = ((3 * g * Dp * (row_p - row_f)) / row_f)**0.5
    print(f"The fluid flow is in the turbulent regime \n The terminal Velocity= {vt:.4f}")

The fluid flow is in the turbulent regime
 The terminal Velocity= 0.8573