## Description
The dataset (downloaded from UCI machine learning repository88) comes from a wastewater treatment plant that uses activated sludge process to remove organic matter and suspended
solids from municipal wastewater. 

In this process (Figure A7), the suspended solids are first physically settled (primary treatment) and then biologically treated to oxidize the biodegradable organic matter (secondary treatment). 

Data from on-line sensors at different stages of the process for 40 variables over 527 days of operation are provided. Seven out of the 38 variables characterize the effluent water quality. 

<div style="text-align:center; margin-top:2rem;">

![water treatment](water-treatment.png)

</div>


## Sensor Data:

- **Effluent:**

    1. DATE        (date)

    2. Q-E         (input flow to plant)

    3. ZN-E        (input Zinc to plant)

    4. PH-E        (input pH to plant)

    5. DBO-E       (input Biological demand of oxygen to plant)

    6. DQO-E       (input chemical demand of oxygen to plant)

    7. SS-E        (input suspended solids to plant)

    8. SSV-E       (input volatile supended solids to plant)

    9. SED-E       (input sediments to plant)

    10. COND-E     (input conductivity to plant)

- **Input to *Primary* Settler**

    11. PH-P       (input pH to primary settler)

    12. DBO-P      (input Biological demand of oxygen to primary settler)

    13. SS-P       (input suspended solids to primary settler)

    14. SSV-P      (input volatile supended solids to primary settler)

    15. SED-P      (input sediments to primary settler)

    16. COND-P     (input conductivity to primary settler)

- **Input to *Secondary* Settler**

    17. PH-D       (input pH to secondary settler)

    18. DBO-D      (input Biological demand of oxygen to secondary settler)

    19. DQO-D      (input chemical demand of oxygen to secondary settler)

    20. SS-D       (input suspended solids to secondary settler)

    21. SSV-D      (input volatile supended solids to secondary settler)

    22. SED-D      (input sediments to secondary settler)

    23. COND-D     (input conductivity to secondary settler)

- **Output from *Secondary* Settler**

    24. PH-S       (output pH)

    25. DBO-S      (output Biological demand of oxygen)

    26. DQO-S      (output chemical demand of oxygen)

    27. SS-S       (output suspended solids)

    28. SSV-S      (output volatile supended solids)

    29. SED-S      (output sediments)

    30. COND-S     (output conductivity)

- **Performance Indicators**

    31. RD-DBO-P   (performance input Biological demand of oxygen in primary settler)

    32. RD-SS-P    (performance input suspended solids to primary settler)

    33. RD-SED-P   (performance input sediments to primary settler)

    34. RD-DBO-S   (performance input Biological demand of oxygen to secondary settler)

    35. RD-DQO-S   (performance input chemical demand of oxygen to secondary settler)

    36. RD-DBO-G   (global performance input Biological demand of oxygen)

    37. RD-DQO-G   (global performance input chemical demand of oxygen)

    38. RD-SS-G    (global performance input suspended solids)

    39. RD-SED-G   (global performance input sediments)


---

## Domain-Specific Data Cleaning Rules:

#### **Biological Oxygen Demand (BOD) vs. Chemical Oxygen Demand (COD)**
   - **Rule**: Biological Oxygen Demand (DBO) should always be lower than or equal to Chemical Oxygen Demand (DQO).
   - **Reason**: BOD measures only the oxygen demand from biodegradable organic matter, while COD measures both biodegradable and non-biodegradable organics.
   - **Action**: If BOD > COD, flag the record for further review or correction, as this suggests a data error.

#### **Consistency in pH Values**
   - **Rule**: pH values should range between 4.5 and 9.5 throughout the treatment stages.
   - **Reason**: In a wastewater treatment plant, extreme pH values (e.g., below 4.5 or above 9.5) are unusual unless the system is under significant chemical stress, which is rare in regular operation. The typical operational pH range for most biological processes is around 6.5–8.5.
   - **Action**: Flag pH values outside the 4.5–9.5 range for verification, as they could be due to sensor errors, chemical spills, or incorrect entries.

#### **Suspended Solids (SS) and Volatile Suspended Solids (VSS) Relationship**
   - **Rule**: Volatile Suspended Solids (VSS) should be less than or equal to Total Suspended Solids (SS).
   - **Reason**: VSS represents the organic portion of total solids, so it should logically be a subset of SS.
   - **Action**: If SSV > SS, flag the data for potential sensor miscalibration or measurement errors.

#### **Flow Rate Consistency**
   - **Rule**: Input flow rate (Q-E) should remain relatively stable, with normal fluctuations due to daily or seasonal variations.
   - **Reason**: Abrupt changes (e.g., >30% deviation) could indicate sensor malfunctions, weather events, or operational disruptions.
   - **Action**: Flag flow rate changes exceeding 30% of the average daily flow for further inspection.

#### **Effluent Water Quality Limits**
   - **Rule**: Effluent parameters should meet regulatory limits (e.g., pH 6.5–8.5, BOD < 20 mg/L, SS < 30 mg/L).
   - **Reason**: Regulatory limits ensure safe discharge, and exceeding them could indicate treatment failures or data errors.
   - **Action**: Flag any effluent parameter that exceeds regulatory limits for potential issues in treatment performance or sensor errors.

#### **Global Performance Indicators (RD-DBO-G, RD-DQO-G, RD-SS-G, RD-SED-G)**
   - **Rule**: Performance metrics should not exceed 100% or fall below 0%.
   - **Reason**: Performance indicators represent the percentage reduction of contaminants, and logically, reductions cannot exceed 100% or be negative (indicating an increase in contaminants).
   - **Action**: Flag any performance metrics that are out of range (below 0% or above 100%) for further review.

#### **Suspended Solids (SS) and Sediments (SED)**
   - **Rule**: Suspended solids and sediments should decrease sequentially from the input stage (SS-E, SED-E) to the output stage (SS-S, SED-S).
   - **Reason**: A well-functioning wastewater treatment plant is expected to progressively remove suspended solids and sediments at each treatment stage (primary, secondary, and final). Increases in SS or SED between stages may indicate anomalies (process malfunction) or data issues.
   - **Action**: Check for increasing values of SS and SED between stages. For example, SS-E > SS-S should hold true, and similarly, SS-P > SS-D > SS-S should also hold for each stage. Flag violations for further investigation.

#### **Conductivity Levels**
   - **Rule**: Conductivity should generally decrease from input to output, except in cases of chemical addition.
   - **Reason**: Treatment typically reduces ionic content, so a rise in conductivity in later stages suggests process issues.
   - **Action**: Flag unexpected increases in conductivity from primary to secondary treatment or in the effluent for further investigation.


---

## Handling Missing Data
   - **Rule**: Missing data should not exceed 5% of total observations for critical variables.
   - **Reason**: Excessive missing data affects process control decisions and model accuracy.
   - **Action**: If more than 5% of data is missing, consider imputing it using appropriate methods like forward fill, backward fill, or interpolation.


---

## Feature Extraction & Feature Engineering

Engineered features, guided by domain knowledge, will enhance the **predictive power** of your models and improve their ability to **capture relationships** critical to the treatment process. Each feature provides more context about how the treatment process operates, allowing for better decision-making and optimization.

#### **Handling Date and Time**
- **Extract Key Temporal Features**:
    - **Day of the Week (from DATE)**: Convert the DATE variable to a day-of-week categorical variable to capture potential weekly patterns in plant operation (e.g., reduced loads on weekends).
    - **Week Number**: Extract the week number from the DATE to analyze potential seasonal variations, such as higher flows during rainy seasons.
    - **Month**: Add a month column to explore monthly trends in effluent quality, flow rate, or treatment performance.
- **New Features**: 
    - Weekday (binary: 1 for Monday–Friday, 0 for Saturday and Sunday)
    - Week number (integer from 1 to 52)
    - Month (integer from 1 to 12)
- **Reason**: Temporal features can help capture potential seasonal variations or differences in operational patterns across days and weeks.


#### **Interaction Terms**
   - **Calculate Organic and Solid Load Ratios**:
     - **Organic Load (kg/day)**: Input flow rate (Q-E) × input Biological Oxygen Demand (DBO-E).
     - **Solid Load (kg/day)**: Input flow rate (Q-E) × input suspended solids (SS-E).
   - **New Features**:
     - Organic Load Ratio (DBO-E relative to Q-E)
     - Solid Load Ratio (SS-E relative to Q-E)
   - **Reason**: These load-based variables help understand how much organic and solid load enters the plant relative to flow, offering insights into potential overloads or underloads at different times.

#### **Performance Ratios and Differences**
   - **Calculate Removal Efficiencies**:
     - Calculate the efficiency of each treatment stage based on BOD, COD, and suspended solids reduction:
       - **BOD Removal Efficiency in Primary Settler** = (DBO-E - DBO-P) / DBO-E × 100%.
       - **BOD Removal Efficiency in Secondary Settler** = (DBO-P - DBO-D) / DBO-P × 100%.
     - Similarly, calculate efficiencies for COD and SS at each stage.
   - **New Features**:
     - BOD Removal Efficiency in Primary Settler (calculated)
     - BOD Removal Efficiency in Secondary Settler (calculated)
     - COD and SS Removal Efficiencies for both stages (calculated)
   - **Reason**: These efficiency measures allow the model to understand treatment performance at each stage, helping diagnose bottlenecks or stages with poor performance.

#### **Efficiency Metrics for Compliance**
   - **Binary Output for Compliance**:
     - **Rule**: Create a binary feature indicating whether the effluent meets regulatory discharge standards for output variables like Biological Oxygen Demand (DBO-S), Chemical Oxygen Demand (DQO-S), and suspended solids (SS-S).
     - **New Feature**:
       - **Compliance Status**: 1 if all effluent parameters meet discharge standards (e.g., DBO-S < 20 mg/L, DQO-S < 100 mg/L, SS-S < 30 mg/L), 0 otherwise.
     - **Reason**: This feature allows the model to easily identify which operational conditions result in compliance or non-compliance, aiding in regulatory monitoring and optimization of treatment processes.


---

## Exercise

In [1]:
# import packages
import pandas as pd
import numpy as np

In [2]:
# Load the dataset
df = pd.read_csv('data.csv')

# Display the first few rows of the dataset
df.head()

,DATE,Q-E,ZN-E,PH-E,DBO-E,DQO-E,SS-E,SSV-E,SED-E,COND-E,...,RD-DQO-G,RD-SS-G,RD-SED-G,PH-S,DBO-S,DQO-S,SS-S,SSV-S,SED-S,COND-S
0,1/1/1990,41230.0,0.35,7.6,120.0,344.0,136.0,54.4,4.5,993,...,71.8,87.5,99.4,7.5,16.0,97.0,17.0,51.8,0.03,903.0
1,1/2/1990,37386.0,1.40,7.9,165.0,470.0,170.0,76.5,4.0,1365,...,79.4,89.4,100.0,7.6,22.0,97.0,18.0,80.6,0.00,1481.0
2,1/3/1990,34535.0,1.00,7.8,232.0,518.0,220.0,65.5,5.5,1617,...,71.8,85.9,99.8,7.5,29.0,146.0,31.0,77.4,0.01,1492.0
3,1/4/1990,32527.0,3.00,7.8,187.0,460.0,180.0,67.8,5.2,1832,...,77.2,83.3,100.0,7.5,28.0,105.0,30.0,82.0,0.00,1590.0
4,1/7/1990,27760.0,1.20,7.6,199.0,466.0,186.0,74.2,4.5,1220,...,73.8,86.6,99.6,7.4,21.0,122.0,25.0,84.0,0.02,1411.0

## Data Cleaning

### Standard Checks

1. **Remove duplicates**

In [3]:
# Count duplicate rows
# TODO
df.duplicated().sum()

1

In [4]:
# Remove duplicate rows
# TODO
df.drop_duplicates(inplace=True)
df

,DATE,Q-E,ZN-E,PH-E,DBO-E,DQO-E,SS-E,SSV-E,SED-E,COND-E,...,RD-DQO-G,RD-SS-G,RD-SED-G,PH-S,DBO-S,DQO-S,SS-S,SSV-S,SED-S,COND-S
0,1/1/1990,41230.0,0.35,7.6,120.0,344.0,136.0,54.4,4.5,993,...,71.8,87.5,99.4,7.5,16.0,97.0,17.0,51.8,0.03,903.0
1,1/2/1990,37386.0,1.40,7.9,165.0,470.0,170.0,76.5,4.0,1365,...,79.4,89.4,100.0,7.6,22.0,97.0,18.0,80.6,0.00,1481.0
2,1/3/1990,34535.0,1.00,7.8,232.0,518.0,220.0,65.5,5.5,1617,...,71.8,85.9,99.8,7.5,29.0,146.0,31.0,77.4,0.01,1492.0
3,1/4/1990,32527.0,3.00,7.8,187.0,460.0,180.0,67.8,5.2,1832,...,77.2,83.3,100.0,7.5,28.0,105.0,30.0,82.0,0.00,1590.0
4,1/7/1990,27760.0,1.20,7.6,199.0,466.0,186.0,74.2,4.5,1220,...,73.8,86.6,99.6,7.4,21.0,122.0,25.0,84.0,0.02,1411.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,10/25/1991,35400.0,0.70,7.6,156.0,364.0,194.0,63.9,5.5,1680,...,82.4,90.7,99.8,7.7,21.0,64.0,18.0,77.8,0.01,1840.0
524,10/26/1991,30964.0,3.30,7.7,220.0,540.0,184.0,62.0,3.5,1445,...,95.0,91.8,95.7,7.9,16.0,27.0,15.0,70.7,0.15,1337.0
525,10/27/1991,35573.0,7.30,7.6,176.0,333.0,178.0,64.0,3.5,1627,...,79.9,-24.9,98.6,7.6,16.0,67.0,23.0,80.0,0.05,1799.0
526,10/29/1991,29801.0,1.60,7.7,172.0,400.0,136.0,70.1,1.5,1402,...,85.3,83.8,96.7,7.7,15.0,59.0,22.0,81.8,0.05,1468.0
527,10/30/1991,31524.0,1.60,7.9,NaN,478.0,204.0,64.7,6.0,1798,...,81.2,89.7,99.2,7.8,NaN,90.0,21.0,85.7,0.05,1568.0

2. **Handle missing values**

In [5]:
# Count missing values for each column
# TODO
df.isna().sum()

DATE         0
Q-E         21
ZN-E         3
PH-E         2
DBO-E       22
DQO-E        6
SS-E         1
SSV-E       11
SED-E       25
COND-E       0
PH-P         0
DBO-P       40
SS-P         0
SSV-P       11
SED-P       24
COND-P       0
PH-D         0
DBO-D       28
DQO-D        9
SS-D         2
SSV-D       13
SED-D       25
COND-D       0
RD-DBO-P    62
RD-SS-P      4
RD-SED-P    27
RD-DBO-S    40
RD-DQO-S    26
RD-DBO-G    36
RD-DQO-G    25
RD-SS-G      7
RD-SED-G    31
PH-S         1
DBO-S       23
DQO-S       18
SS-S         5
SSV-S       17
SED-S       28
COND-S       1
dtype: int64

In [6]:
""" # handle missing values as you see fit
#! BONUS ALERT. Bonus if you use domain knowledge for imputation instead of simple average or interpolation for at least [3] different columns.
# TODO
# Rule: Biological Oxygen Demand (DBO) vs. Chemical Oxygen Demand (DQO) To ensure DBO ≤ DQO, we’ll define a function that corrects or imputes DBO based on DQO and vice versa.
def impute_dbo_dqo(df):
    # Assuming DBO and DQO columns are named 'DBO-E' and 'DQO-E'
    for index, row in df.iterrows():
        if pd.isna(row['DBO-E']) and not pd.isna(row['DQO-E']):
            # Set missing DBO as a fraction of DQO, e.g., 70%
            df.at[index, 'DBO-E'] = row['DQO-E'] * 0.7
        elif pd.isna(row['DQO-E']) and not pd.isna(row['DBO-E']):
            # Set missing DQO as a fraction above DBO, e.g., 1.5 times
            df.at[index, 'DQO-E'] = row['DBO-E'] * 1.5
        elif not pd.isna(row['DBO-E']) and not pd.isna(row['DQO-E']):
            # Correct any DBO > DQO errors by setting DBO = DQO if necessary
            if row['DBO-E'] > row['DQO-E']:
                df.at[index, 'DBO-E'] = row['DQO-E']
    return df

#Rule: pH Value Consistency Impute missing pH values within the acceptable range (4.5–9.5) and interpolate from other stages.
def impute_ph(df, columns):
    for col in columns:
        # Fill missing pH values within range by interpolating
        df[col] = df[col].apply(lambda x: 7.0 if pd.isna(x) else x)  # Default to neutral if missing
        df[col] = df[col].apply(lambda x: 4.5 if x < 4.5 else 9.5 if x > 9.5 else x)  # Clamping values
    return df

#Rule: Suspended Solids (SS) and Volatile Suspended Solids (VSS) Ensure VSS ≤ SS by setting missing values based on expected fractions.
def impute_ss_vss(df, ss_col='SS-E', vss_col='SSV-E'):
    for index, row in df.iterrows():
        if pd.isna(row[ss_col]) and not pd.isna(row[vss_col]):
            df.at[index, ss_col] = row[vss_col] * 1.2  # Assume VSS is typically ~80% of SS
        elif pd.isna(row[vss_col]) and not pd.isna(row[ss_col]):
            df.at[index, vss_col] = row[ss_col] * 0.8
        elif not pd.isna(row[ss_col]) and not pd.isna(row[vss_col]):
            if row[vss_col] > row[ss_col]:
                df.at[index, vss_col] = row[ss_col]
    return df

#Now apply these functions to your dataset.
# Impute DBO and DQO based on their relationship
data = impute_dbo_dqo(df)

# Impute pH values in relevant columns
ph_columns = ['PH-E', 'PH-P', 'PH-D', 'PH-S']
data = impute_ph(data, ph_columns)

# Impute SS and VSS
data = impute_ss_vss(data, ss_col='SS-E', vss_col='SSV-E')
data = impute_ss_vss(data, ss_col='SS-P', vss_col='SSV-P')
data = impute_ss_vss(data, ss_col='SS-D', vss_col='SSV-D')
data = impute_ss_vss(data, ss_col='SS-S', vss_col='SSV-S')

# Check for any remaining missing values
print("Remaining missing values:\n", data.isna().sum())
"""

' # handle missing values as you see fit\n#! BONUS ALERT. Bonus if you use domain knowledge for imputation instead of simple average or interpolation for at least [3] different columns.\n# TODO\n# Rule: Biological Oxygen Demand (DBO) vs. Chemical Oxygen Demand (DQO) To ensure DBO ≤ DQO, we’ll define a function that corrects or imputes DBO based on DQO and vice versa.\ndef impute_dbo_dqo(df):\n    # Assuming DBO and DQO columns are named \'DBO-E\' and \'DQO-E\'\n    for index, row in df.iterrows():\n        if pd.isna(row[\'DBO-E\']) and not pd.isna(row[\'DQO-E\']):\n            # Set missing DBO as a fraction of DQO, e.g., 70%\n            df.at[index, \'DBO-E\'] = row[\'DQO-E\'] * 0.7\n        elif pd.isna(row[\'DQO-E\']) and not pd.isna(row[\'DBO-E\']):\n            # Set missing DQO as a fraction above DBO, e.g., 1.5 times\n            df.at[index, \'DQO-E\'] = row[\'DBO-E\'] * 1.5\n        elif not pd.isna(row[\'DBO-E\']) and not pd.isna(row[\'DQO-E\']):\n            # Correct any DBO > DQO errors by setting DBO = DQO if necessary\n            if row[\'DBO-E\'] > row[\'DQO-E\']:\n                df.at[index, \'DBO-E\'] = row[\'DQO-E\']\n    return df\n\n#Rule: pH Value Consistency Impute missing pH values within the acceptable range (4.5–9.5) and interpolate from other stages.\ndef impute_ph(df, columns):\n    for col in columns:\n        # Fill missing pH values within range by interpolating\n        df[col] = df[col].apply(lambda x: 7.0 if pd.isna(x) else x)  # Default to neutral if missing\n        df[col] = df[col].apply(lambda x: 4.5 if x < 4.5 else 9.5 if x > 9.5 else x)  # Clamping values\n    return df\n\n#Rule: Suspended Solids (SS) and Volatile Suspended Solids (VSS) Ensure VSS ≤ SS by setting missing values based on expected fractions.\ndef impute_ss_vss(df, ss_col=\'SS-E\', vss_col=\'SSV-E\'):\n    for index, row in df.iterrows():\n        if pd.isna(row[ss_col]) and not pd.isna(row[vss_col]):\n            df.at[index, ss_col] = row[vss_col] * 1.2  # Assume VSS is typically ~80% of SS\n        elif pd.isna(row[vss_col]) and not pd.isna(row[ss_col]):\n            df.at[index, vss_col] = row[ss_col] * 0.8\n        elif not pd.isna(row[ss_col]) and not pd.isna(row[vss_col]):\n            if row[vss_col] > row[ss_col]:\n                df.at[index, vss_col] = row[ss_col]\n    return df\n\n#Now apply these functions to your dataset.\n# Impute DBO and DQO based on their relationship\ndata = impute_dbo_dqo(df)\n\n# Impute pH values in relevant columns\nph_columns = [\'PH-E\', \'PH-P\', \'PH-D\', \'PH-S\']\ndata = impute_ph(data, ph_columns)\n\n# Impute SS and VSS\ndata = impute_ss_vss(data, ss_col=\'SS-E\', vss_col=\'SSV-E\')\ndata = impute_ss_vss(data, ss_col=\'SS-P\', vss_col=\'SSV-P\')\ndata = impute_ss_vss(data, ss_col=\'SS-D\', vss_col=\'SSV-D\')\ndata = impute_ss_vss(data, ss_col=\'SS-S\', vss_col=\'SSV-S\')\n\n# Check for any remaining missing values\nprint("Remaining missing values:\n", data.isna().sum())\n'

In [19]:
# impute with mean for numeric columns only
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())
df.isna().sum()

DATE                        0
Q-E                         0
ZN-E                        0
PH-E                        0
DBO-E                       0
DQO-E                       0
SS-E                        0
SSV-E                       0
SED-E                       0
COND-E                      0
PH-P                        0
DBO-P                       0
SS-P                        0
SSV-P                       0
SED-P                       0
COND-P                      0
PH-D                        0
DBO-D                       0
DQO-D                       0
SS-D                        0
SSV-D                       0
SED-D                       0
COND-D                      0
RD-DBO-P                    0
RD-SS-P                     0
RD-SED-P                    0
RD-DBO-S                    0
RD-DQO-S                    0
RD-DBO-G                    0
RD-DQO-G                    0
RD-SS-G                     0
RD-SED-G                    0
PH-S                        0
DBO-S                       0
DQO-S                       0
SS-S                        0
SSV-S                       0
SED-S                       0
COND-S                      0
FLAG                        0
Day_of_Week                 0
Week_Number                 0
Month                       0
Compliance_Status           0
BOD_Efficiency_Primary      0
BOD_Efficiency_Secondary    0
BOD_Input_Output_Ratio      0
SS_Input_Output_Ratio       0
dtype: int64


3. **Standardize the date column**

In [8]:
# convert all columns except 'DATE' to float
df.loc[:, df.columns != 'DATE'] = df.loc[:, df.columns != 'DATE'].astype(float)


# convert column to datetime
df['DATE'] = pd.to_datetime(df['DATE'])

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 527 entries, 0 to 527
Data columns (total 39 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      527 non-null    datetime64[ns]
 1   Q-E       527 non-null    float64
 2   ZN-E      527 non-null    float64
 3   PH-E      527 non-null    float64
 4   DBO-E     527 non-null    float64
 5   DQO-E     527 non-null    float64
 6   SS-E      527 non-null    float64
 7   SSV-E     527 non-null    float64
 8   SED-E     527 non-null    float64
 9   COND-E    527 non-null    int64
 10  PH-P      527 non-null    float64
 11  DBO-P     527 non-null    float64
 12  SS-P      527 non-null    int64
 13  SSV-P     527 non-null    float64
 14  SED-P     527 non-null    float64
 15  COND-P    527 non-null    int64
 16  PH-D      527 non-null    float64
 17  DBO-D     527 non-null    float64
 18  DQO-D     527 non-null    float64
 19  SS-D      527 non-null    float64
 20  SSV-D     527 non-null    float64
 21  SED-D     527 non-null    float64
 22  COND-D    527 non-null    int64
 23  RD-DBO-P  527 non-null    float64
 24  RD-SS-P   527 non-null    float64
 25  RD-SED-P  527 non-null    float64
 26  RD-DBO-S  527 non-null    float64
 27  RD-DQO-S  527 non-null    float64
 28  RD-DBO-G  527 non-null    float64
 29  RD-DQO-G  527 non-null    float64
 30  RD-SS-G   527 non-null    float64
 31  RD-SED-G  527 non-null    float64
 32  PH-S      527 non-null    float64
 33  DBO-S     527 non-null    float64
 34  DQO-S     527 non-null    float64
 35  SS-S      527 non-null    float64
 36  SSV-S     527 non-null    float64
 37  SED-S     527 non-null    float64
 38  COND-S    527 non-null    float64
dtypes: datetime64[ns](1), float64(34), int64(4)
memory usage: 164.7 KB

### Domain-specific Checks

1. **Ensure BOD is less than or equal to COD**

In [9]:
# Ensure BOD (DBO-E) is less than or equal to COD (DQO-E) at each stage
# TODO: Flag records where DBO-E > DQO-E
df['FLAG'] = np.where(df['DBO-E'] > df['DQO-E'], 1, 0)
df

,DATE,Q-E,ZN-E,PH-E,DBO-E,DQO-E,SS-E,SSV-E,SED-E,COND-E,...,RD-SS-G,RD-SED-G,PH-S,DBO-S,DQO-S,SS-S,SSV-S,SED-S,COND-S,FLAG
0,1990-01-01,41230.0,0.35,7.6,120.000000,344.0,136.0,54.4,4.5,993,...,87.5,99.4,7.5,16.000000,97.0,17.0,51.8,0.03,903.0,0
1,1990-01-02,37386.0,1.40,7.9,165.000000,470.0,170.0,76.5,4.0,1365,...,89.4,100.0,7.6,22.000000,97.0,18.0,80.6,0.00,1481.0,0
2,1990-01-03,34535.0,1.00,7.8,232.000000,518.0,220.0,65.5,5.5,1617,...,85.9,99.8,7.5,29.000000,146.0,31.0,77.4,0.01,1492.0,0
3,1990-01-04,32527.0,3.00,7.8,187.000000,460.0,180.0,67.8,5.2,1832,...,83.3,100.0,7.5,28.000000,105.0,30.0,82.0,0.00,1590.0,0
4,1990-01-07,27760.0,1.20,7.6,199.000000,466.0,186.0,74.2,4.5,1220,...,86.6,99.6,7.4,21.000000,122.0,25.0,84.0,0.02,1411.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,1991-10-25,35400.0,0.70,7.6,156.000000,364.0,194.0,63.9,5.5,1680,...,90.7,99.8,7.7,21.000000,64.0,18.0,77.8,0.01,1840.0,0
524,1991-10-26,30964.0,3.30,7.7,220.000000,540.0,184.0,62.0,3.5,1445,...,91.8,95.7,7.9,16.000000,27.0,15.0,70.7,0.15,1337.0,0
525,1991-10-27,35573.0,7.30,7.6,176.000000,333.0,178.0,64.0,3.5,1627,...,-24.9,98.6,7.6,16.000000,67.0,23.0,80.0,0.05,1799.0,0
526,1991-10-29,29801.0,1.60,7.7,172.000000,400.0,136.0,70.1,1.5,1402,...,83.8,96.7,7.7,15.000000,59.0,22.0,81.8,0.05,1468.0,0
527,1991-10-30,31524.0,1.60,7.9,190.130693,478.0,204.0,64.7,6.0,1798,...,89.7,99.2,7.8,19.988095,90.0,21.0,85.7,0.05,1568.0,0


2. **Ensure pH is within the range 4.5 to 9.5**

In [10]:
# Ensure pH values are within the acceptable range (6.0 to 9.0)
# TODO: Flag records where PH-E is outside this range
df['FLAG'] = np.where((df['PH-E'] < 6.0) | (df['PH-E'] > 9.0), 1, 0)


3. **Ensure Volatile Suspended Solids (SSV) are less than or equal to Total Suspended Solids (SS)**

In [11]:
# Ensure SSV-E is less than or equal to SS-E at each stage
# TODO: Flag records where SSV-E > SS-E
df['FLAG'] = np.where(df['SSV-E'] > df['SS-E'], 1, 0)


4. **Check for negative or out-of-range global performance indicators**

In [12]:
# Ensure global performance indicators (RD-SS-G) are between 0% and 100%
# TODO: Flag records where global reduced SS (RD-SS-G) is out of range
df['FLAG'] = np.where((df['RD-SS-G'] < 0) | (df['RD-SS-G'] > 100), 1, 0)

In [13]:
# show the info of the dataset after cleaning
# TODO
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 527 entries, 0 to 527
Data columns (total 40 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      527 non-null    datetime64[ns]
 1   Q-E       527 non-null    float64
 2   ZN-E      527 non-null    float64
 3   PH-E      527 non-null    float64
 4   DBO-E     527 non-null    float64
 5   DQO-E     527 non-null    float64
 6   SS-E      527 non-null    float64
 7   SSV-E     527 non-null    float64
 8   SED-E     527 non-null    float64
 9   COND-E    527 non-null    int64
 10  PH-P      527 non-null    float64
 11  DBO-P     527 non-null    float64
 12  SS-P      527 non-null    int64
 13  SSV-P     527 non-null    float64
 14  SED-P     527 non-null    float64
 15  COND-P    527 non-null    int64
 16  PH-D      527 non-null    float64
 17  DBO-D     527 non-null    float64
 18  DQO-D     527 non-null    float64
 19  SS-D      527 non-null    float64
 20  SSV-D     527 non-null    float64
 21  SED-D     527 non-null    float64
 22  COND-D    527 non-null    int64
 23  RD-DBO-P  527 non-null    float64
 24  RD-SS-P   527 non-null    float64
 25  RD-SED-P  527 non-null    float64
 26  RD-DBO-S  527 non-null    float64
 27  RD-DQO-S  527 non-null    float64
 28  RD-DBO-G  527 non-null    float64
 29  RD-DQO-G  527 non-null    float64
 30  RD-SS-G   527 non-null    float64
 31  RD-SED-G  527 non-null    float64
 32  PH-S      527 non-null    float64
 33  DBO-S     527 non-null    float64
 34  DQO-S     527 non-null    float64
 35  SS-S      527 non-null    float64
 36  SSV-S     527 non-null    float64
 37  SED-S     527 non-null    float64
 38  COND-S    527 non-null    float64
 39  FLAG      527 non-null    int32
dtypes: datetime64[ns](1), float64(34), int32(1), int64(4)
memory usage: 166.7 KB

In [14]:
# save the cleaned dataset to CSV
# TODO
df.to_csv('cleaned_data.csv', index=False)

## Feature Engineering

1. **Extract day-of-week, week number, and month from the date**

In [15]:
# Convert DATE to datetime format
df['DATE'] = pd.to_datetime(df['DATE'], format='%Y-%m-%d')

# Extract day-of-week, week number, and month from the date
# TODO: Create new features for Day_of_Week, Week_Number, and Month
df['Day_of_Week'] = df['DATE'].dt.day_name()
df['Week_Number'] = df['DATE'].dt.isocalendar().week
df['Month'] = df['DATE'].dt.month_name()

df

,DATE,Q-E,ZN-E,PH-E,DBO-E,DQO-E,SS-E,SSV-E,SED-E,COND-E,...,DBO-S,DQO-S,SS-S,SSV-S,SED-S,COND-S,FLAG,Day_of_Week,Week_Number,Month
0,1990-01-01,41230.0,0.35,7.6,120.000000,344.0,136.0,54.4,4.5,993,...,16.000000,97.0,17.0,51.8,0.03,903.0,0,Monday,1,January
1,1990-01-02,37386.0,1.40,7.9,165.000000,470.0,170.0,76.5,4.0,1365,...,22.000000,97.0,18.0,80.6,0.00,1481.0,0,Tuesday,1,January
2,1990-01-03,34535.0,1.00,7.8,232.000000,518.0,220.0,65.5,5.5,1617,...,29.000000,146.0,31.0,77.4,0.01,1492.0,0,Wednesday,1,January
3,1990-01-04,32527.0,3.00,7.8,187.000000,460.0,180.0,67.8,5.2,1832,...,28.000000,105.0,30.0,82.0,0.00,1590.0,0,Thursday,1,January
4,1990-01-07,27760.0,1.20,7.6,199.000000,466.0,186.0,74.2,4.5,1220,...,21.000000,122.0,25.0,84.0,0.02,1411.0,0,Sunday,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,1991-10-25,35400.0,0.70,7.6,156.000000,364.0,194.0,63.9,5.5,1680,...,21.000000,64.0,18.0,77.8,0.01,1840.0,0,Friday,43,October
524,1991-10-26,30964.0,3.30,7.7,220.000000,540.0,184.0,62.0,3.5,1445,...,16.000000,27.0,15.0,70.7,0.15,1337.0,0,Saturday,43,October
525,1991-10-27,35573.0,7.30,7.6,176.000000,333.0,178.0,64.0,3.5,1627,...,16.000000,67.0,23.0,80.0,0.05,1799.0,1,Sunday,43,October
526,1991-10-29,29801.0,1.60,7.7,172.000000,400.0,136.0,70.1,1.5,1402,...,15.000000,59.0,22.0,81.8,0.05,1468.0,0,Tuesday,44,October
527,1991-10-30,31524.0,1.60,7.9,190.130693,478.0,204.0,64.7,6.0,1798,...,19.988095,90.0,21.0,85.7,0.05,1568.0,0,Wednesday,44,October


2. **Create binary compliance indicator**

In [16]:
# Create a binary feature for regulatory compliance
# TODO: Create Compliance_Status based on regulatory discharge limits
df['Compliance_Status'] = np.where((df['DBO-E'] <= 60) & (df['DQO-E'] <= 90) & (df['SS-E'] <= 90) & (df['SSV-E'] <= 30) & (df['PH-E'] >= 6) & (df['PH-E'] <= 9), 'Compliant', 'Non-Compliant')


3. **Calculate BOD removal efficiency in primary and secondary settlers**

In [17]:
# Calculate BOD removal efficiency in primary and secondary settlers
# TODO: Create features for BOD_Efficiency_Primary and BOD_Efficiency_Secondary
df['BOD_Efficiency_Primary'] = ((df['DBO-E'] - df['DBO-P']) / df['DBO-E']) * 100
df['BOD_Efficiency_Secondary'] = ((df['DBO-P'] - df['DBO-D']) / df['DBO-P']) * 100

df

,DATE,Q-E,ZN-E,PH-E,DBO-E,DQO-E,SS-E,SSV-E,SED-E,COND-E,...,SSV-S,SED-S,COND-S,FLAG,Day_of_Week,Week_Number,Month,Compliance_Status,BOD_Efficiency_Primary,BOD_Efficiency_Secondary
0,1990-01-01,41230.0,0.35,7.6,120.000000,344.0,136.0,54.4,4.5,993,...,51.8,0.03,903.0,0,Monday,1,January,Non-Compliant,-71.839493,40.667162
1,1990-01-02,37386.0,1.40,7.9,165.000000,470.0,170.0,76.5,4.0,1365,...,80.6,0.00,1481.0,0,Tuesday,1,January,Non-Compliant,-24.974177,24.348008
2,1990-01-03,34535.0,1.00,7.8,232.000000,518.0,220.0,65.5,5.5,1617,...,77.4,0.01,1492.0,0,Wednesday,1,January,Non-Compliant,0.862069,32.608696
3,1990-01-04,32527.0,3.00,7.8,187.000000,460.0,180.0,67.8,5.2,1832,...,82.0,0.00,1590.0,0,Thursday,1,January,Non-Compliant,-17.112299,13.242009
4,1990-01-07,27760.0,1.20,7.6,199.000000,466.0,186.0,74.2,4.5,1220,...,84.0,0.02,1411.0,0,Sunday,1,January,Non-Compliant,-13.065327,38.222222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,1991-10-25,35400.0,0.70,7.6,156.000000,364.0,194.0,63.9,5.5,1680,...,77.8,0.01,1840.0,0,Friday,43,October,Non-Compliant,-8.333333,47.337278
524,1991-10-26,30964.0,3.30,7.7,220.000000,540.0,184.0,62.0,3.5,1445,...,70.7,0.15,1337.0,0,Saturday,43,October,Non-Compliant,6.269367,40.667162
525,1991-10-27,35573.0,7.30,7.6,176.000000,333.0,178.0,64.0,3.5,1627,...,80.0,0.05,1799.0,1,Sunday,43,October,Non-Compliant,3.409091,28.030178
526,1991-10-29,29801.0,1.60,7.7,172.000000,400.0,136.0,70.1,1.5,1402,...,81.8,0.05,1468.0,0,Tuesday,44,October,Non-Compliant,-5.813953,32.417582
527,1991-10-30,31524.0,1.60,7.9,190.130693,478.0,204.0,64.7,6.0,1798,...,85.7,0.05,1568.0,0,Wednesday,44,October,Non-Compliant,-8.455604,40.667162


4. **Calculate input-output ratios for BOD and suspended solids**

In [21]:
# Calculate BOD and suspended solids input-output ratios
# TODO: Create features for BOD_Input_Output_Ratio and SS_Input_Output_Ratio
df['BOD_Input_Output_Ratio'] = df['DBO-D'] / df['DBO-E']
df['SS_Input_Output_Ratio'] = df['SS-D'] / df['SS-E']


df.head()

,DATE,Q-E,ZN-E,PH-E,DBO-E,DQO-E,SS-E,SSV-E,SED-E,COND-E,...,COND-S,FLAG,Day_of_Week,Week_Number,Month,Compliance_Status,BOD_Efficiency_Primary,BOD_Efficiency_Secondary,BOD_Input_Output_Ratio,SS_Input_Output_Ratio
0,1990-01-01,41230.0,0.35,7.6,120.0,344.0,136.0,54.4,4.5,993,...,903.0,0,Monday,1,January,Non-Compliant,-71.839493,40.667162,1.019572,0.514706
1,1990-01-02,37386.0,1.40,7.9,165.0,470.0,170.0,76.5,4.0,1365,...,1481.0,0,Tuesday,1,January,Non-Compliant,-24.974177,24.348008,0.945455,0.564706
2,1990-01-03,34535.0,1.00,7.8,232.0,518.0,220.0,65.5,5.5,1617,...,1492.0,0,Wednesday,1,January,Non-Compliant,0.862069,32.608696,0.668103,0.345455
3,1990-01-04,32527.0,3.00,7.8,187.0,460.0,180.0,67.8,5.2,1832,...,1590.0,0,Thursday,1,January,Non-Compliant,-17.112299,13.242009,1.016043,0.555556
4,1990-01-07,27760.0,1.20,7.6,199.0,466.0,186.0,74.2,4.5,1220,...,1411.0,0,Sunday,1,January,Non-Compliant,-13.065327,38.222222,0.698492,0.505376